site_name: Prefeitura de Águas Lindas de Goiás
repo_url: https://github.com/Interacao-Humano-Computador/2020.1-Prefeiturade-Aguas-Lindas-de-Goias 
repo_name: 2020.1-Prefeiturade-Aguas-Lindas-de-Goias 
nav:
  - Home: index.md
  - Planejamento:
    - Cronograma: planejamento/cronograma.md
    - Sites Avaliados: planejamento/sites.md
    - Site Selecionado: planejamento/site.md
    - Processo de Design: planejamento/processo.md
  - Análise de tarefas:
    - HTA: analise_tarefas/HTA.md
    - KLM: analise_tarefas/KLM.md
    - CTT: analise_tarefas/CTT.md
    - CMN-GOMS: analise_tarefas/CMN_GOMS.md
    - CPM-GOMS: analise_tarefas/CPM_GOMS.md  
  - Perfil do usuário: 
    - Questionário: perfil_usuario/questionario.md
    - Personas: perfil_usuario/perfil_personas.md
    - Entrevista: perfil_usuario/entrevista.md
  - Apresentações:
    - Apresentação - Primeira entrega (21/09): apresentacoes/apresentacao-21-09.md

  
theme:
  logo: 'imagens/favicon.png' 
  name: "material"
  language: "pt"
  icon:
    repo: fontawesome/brands/github
  palette:
    primary: "black"
    accent: "amber"
markdown_extensions:
  - attr_list