site_name: Prefeitura de Águas Lindas de Goiás
repo_url: https://github.com/Interacao-Humano-Computador/2020.1-Prefeiturade-Aguas-Lindas-de-Goias
repo_name: 2020.1-Prefeiturade-Aguas-Lindas-de-Goias
nav:
  - Home: index.md
  - Cronograma de atividades: planejamento/cronograma.md
  - Planejamento:
    - Sites Avaliados: planejamento/sites.md
    - Site Selecionado: planejamento/site.md
    - Processo de Design: planejamento/processo.md
  - Perfil do usuário:
    - Questionário: perfil_usuario/questionario.md
    - Personas: perfil_usuario/perfil_personas.md
    - Entrevista: perfil_usuario/entrevista.md
  - Análise de tarefas:
    - HTA: analise_tarefas/HTA.md
    - KLM: analise_tarefas/KLM.md
    - CTT: analise_tarefas/CTT.md
    - CMN-GOMS: analise_tarefas/CMN_GOMS.md
    - CPM-GOMS: analise_tarefas/CPM_GOMS.md
  - Análise de requisitos:
    - Características da plataforma: analise_requisitos/caracteristicas_plataforma.md
    - Princípios e diretrizes do projeto: analise_requisitos/principios_diretrizes.md
    - Metas de usabilidade: analise_requisitos/metas_usabilidade.md
    - Guia de estilo: analise_requisitos/guia_estilo.md
  - Apresentações:
    - Apresentação - Primeira entrega (21/09): apresentacoes/apresentacao-21-09.md
    - Apresentação - Segunda entrega (05/10): apresentacoes/apresentacao-05-10.md
    - Apresentação - Terceira entrega (15/19): apresentacoes/apresentacao-15-10.md


theme:
  logo: 'imagens/favicon.png'
  name: "material"
  language: "pt"
  icon:
    repo: fontawesome/brands/github
  palette:
    primary: "black"
    accent: "amber"
markdown_extensions:
  - attr_list
  - pymdownx.details
