site_name: Prefeitura de Águas Lindas de Goiás
repo_url: https://github.com/Interacao-Humano-Computador/2020.1-Prefeiturade-Aguas-Lindas-de-Goias
repo_name: 2020.1-Prefeiturade-Aguas-Lindas-de-Goias
nav:
  - Home: index.md
  - Cronograma de atividades: planejamento/cronograma.md
  - Planejamento:
    - Sites Avaliados: planejamento/sites.md
    - Site Selecionado: planejamento/site.md
    - Processo de Design: planejamento/processo.md
  - Perfil do usuário:
    - Questionário: perfil_usuario/questionario.md
    - Personas: perfil_usuario/perfil_personas.md
    - Entrevista: perfil_usuario/entrevista.md
  - Análise de requisitos:
    - Características da plataforma: analise_requisitos/caracteristicas_plataforma.md
    - Princípios e diretrizes do projeto: analise_requisitos/principios_diretrizes.md
    - Metas de usabilidade: analise_requisitos/metas_usabilidade.md
    - Guia de estilo: analise_requisitos/guia_estilo.md
  - Análise de tarefas:
    - Análise das tarefas: analise_tarefas/AnaliseTarefas.md
    - Planejamento e avaliação das análises das tarefas: teste_usabilidade_tarefas/teste_usabilidade_principal.md
  - Storyboards: 
    - Storyboards: storyboard/storyboard_principal.md
    - Planejamento e avaliação dos Storyboards: storyboard/av_storyboard_principal.md
  - Protótipos de papel:
    - Protótipos de papel: prototipo_papel/prototipo_principal.md
    - Planejamento e avaliação dos protótipos de papel: prototipo_papel/av_prototipo_principal.md
  - Protótipos de Alta-Fidelidade:
    - Protótipos de Alta-Fidelidade: prototipo_alta_fidelidade/prototipo_alta_fidelidade_principal.md
    - Planejamento e avaliação dos protótipos Alta-Fidelidade: prototipo_alta_fidelidade/av_prototipo_alta_fidelidade_principal.md
  - Apresentações:
    - Primeira entrega (21/09): apresentacoes/apresentacao-21-09.md
    - Segunda entrega (05/10): apresentacoes/apresentacao-05-10.md
    - Terceira entrega (15/10): apresentacoes/apresentacao-15-10.md
    - Quarta entrega (29/10): apresentacoes/apresentacao-29-10.md
    - Quinta entrega (12/11): apresentacoes/apresentacao-12-11.md



theme:
  logo: 'imagens/favicon.png'
  name: "material"
  language: "pt"
  icon:
    repo: fontawesome/brands/github
  palette:
    primary: "black"
    accent: "amber"
markdown_extensions:
  - attr_list
  - pymdownx.details
