site_name: Prefeitura de Águas Lindas de Goiás
repo_url: https://github.com/Interacao-Humano-Computador/2020.1-Prefeiturade-Aguas-Lindas-de-Goias 
repo_name: 2020.1-Prefeiturade-Aguas-Lindas-de-Goias 
nav:
  - Home: index.md
  - Planejamento:
    - Cronograma: planejamento/cronograma.md
    - Sites Avaliados: planejamento/sites.md
    - Site Selecionado: planejamento/site.md
    - Processo de Design: planejamento/processo.md
  - Apresentacoes:
    - Apresentacao (21/09): apresentacoes/apresentacao-21-09.md

theme:
  logo: 'imagens/favicon.png' 
  name: "material"
  language: "pt"
  icon:
    repo: fontawesome/brands/github
  palette:
    primary: "black"
    accent: "amber"
markdown_extensions:
  - attr_list